amp-labs/openapi

api/api.yaml, api/write.yaml
The spec was updated while I was setting this repo up, so we need to update it
=> Update openapi specs

config/config.yaml
Tested as part of this PR 
https://github.com/amp-labs/server/pull/1039
=> [ENG-1242] Backfill definition

.gitignore
This just adds a `.gitignore` file. It's a template for the common editors (vscode, jetbrains, vim, emacs)
=> chore: Add a .gitignore file

.github/workflows/trigger-docs-gen.yml, .husky/pre-commit, README.md, package.json, pnpm-lock.yaml
**What:** 
1. Adds a gh workflow to trigger auto docs generation in the `docs` repo 
2. Also adds a pre-commit hook to generate json version of the openapi spec
=> [ENG-1340] feat: add gh workflow to trigger auto docs generation

api/generated/api.json, catalog/catalog.yaml
This is just so we can have a docsURL in our catalog
=> feat: Add BasicAuthOpts

config/config.yaml
=> chore: Rename backfill and defaultPeriod in config

api/generated/api.json, manifest/manifest.yaml
This PR is blocking https://github.com/amp-labs/server/pull/1309/files
make lint, make gen
=> Bug: fix openapi backfill added to hydrated revision. 

api/api.yaml, api/generated/api.json
With related PR https://github.com/amp-labs/server/pull/1434
Use sourceYAML as alternative to create integration or update revision.
=> Soureyaml to Create Integration and Update Revision

api/api.yaml, api/generated/api.json
=> fix: Correct spelling

api/api.yaml, api/generated/api.json
Corresponding openapi changes for https://github.com/amp-labs/server/pull/1745
=> feat: Add scopes to API Key

api/generated/api.json, config/config.yaml
See https://ampersand.slab.com/posts/read-all-fields-for-an-object-bnwm68j2
=> [ENG-1618] feat: add SelectedFieldsAutoConfig

api/generated/api.json, manifest/manifest.yaml
=> Revert "[ENG-1618] feat: Add the selectedFieldsAuto field"

api/generated/api.json, manifest/manifest.yaml
See https://ampersand.slab.com/posts/inherited-mapping-and-builder-defined-mapping-9qx84i05
=> feat: Add fields to support mapping inheritence

api/generated/api.json, config/config.yaml
This reverts commit 859f3139f9d5807e5d1781ba4dd7810c407f0a9c.
=> Revert "add more fields for builder-defined mapped objects"

api/generated/api.json, manifest/manifest.yaml
This PR adds x-go-type-skip-optional-pointer to mapped fields
=> feat: Add x-go-type-skip-optional-pointer

webhook/webhook.yaml
=> chore: remove result entry field reference to defined objects, instead use generic objects

webhook/webhook.yaml
This PR renames installationLastUpdated to installationUpdateTime
=> feat: rename installationLastUpdated to installationUpdateTime

api/api.yaml, api/generated/api.json
Added Oauth2AuthorizationCode to `GenerateConnection` endpoint
I ran `make lint` and `make gen`
=> [ENG-1752] OAuthAuthCode in GenerateConnection

api/api.yaml, api/generated/api.json
I ran `make lint` and `make gen`
=> [ENG-1752] Update Getconnection with Query Params

api/api.yaml, api/generated/api.json
https://linear.app/ampersand/issue/ENG-1776/typescript-sdk-for-api#comment-8666460e
=> [ENG-1774] chore: ignore methods from sdk

config/config.yaml
this needed for the server code to work.
=> Add back x-go-type: any

manifest/generated/manifest.json, webhook/generated/webhook.json, webhook/webhook.yaml
=> [ENG-1891]rename enum var name annotation

api/generated/api.json, manifest/manifest.yaml
This field is descoped for MVP
=> [ENG-2006] Remove inheritFields

config/generated/config.json, webhook/generated/webhook.json, webhook/webhook.yaml
@laurenzlong  We have discussed having an id field, but we didn't anticipate that we would have to change the openapi spec.
If you think this is needed, please approve, otherwise, we can discuss this point.
=> [ENG-2009] Add id to result entry in case of Delete event

.gitignore, api/api.yaml, api/generated/api.json
=> [ENG-1917] Add more examples and descriptions to API fields

api/generated/api.json, catalog/catalog.yaml, catalog/generated/catalog.json, package-lock.json
https://github.com/amp-labs/connectors/pull/1519
=> [CON-1616] feat(catalog): ModuleInfo

api/api.yaml, api/generated/api.json, catalog/generated/catalog.json
To reflect the payload from API
=> Update connection endpoint

api/api.yaml, api/generated/api.json
Previous PR added new type to previously reference type which broke. thix ix fixing it.
=> fix Generate Connection Ref

api/api.yaml
Doesn't seem like the overlay is working & it's not clear why, so adding this directly here
=> chore: add listBuilders to sdk

.husky/pre-commit, api/generated/api.json, catalog/catalog.yaml, catalog/generated/catalog.json
=> [ENG-2137] feat: Allow defining required metadata in catalog

api/generated/api.json, catalog/generated/catalog.json, config/config.yaml, config/generated/config.json
We need config object to be defined in order to enable general use case.
=> [ENG-2267] Subscribe Config 

api/api.yaml, catalog/catalog.yaml
This adds the fields discussed here: https://ampersand.slab.com/posts/supporting-non-standard-auth-types-qt8md7qp
=> [ENG-2343] feat: Add custom auth options

api/api.yaml, api/generated/api.json
This adds the fields discussed here: https://ampersand.slab.com/posts/outpost-exploration-s76qaw72
=> [ENG-2260] feat: Add kinesis fields to destination

api/generated/api.json, config/config.yaml, config/generated/config.json
=> Revert "[ENG-2218] chore: add enabled to read"

api/api.yaml, api/generated/api.json, catalog/generated/catalog.json
This PR adds specs for the listInstallations endpoint with query parameters. This endpoint will list all installations from all of the integration that matches group.
=> [ENG-2365] List installations with query params

api/api.yaml, api/generated/api.json, catalog/generated/catalog.json
This PR add GetIntegration API endpoint
=> [ENG-2208] Get integration endpoint

api/api.yaml, api/generated/api.json
- added 'JWT key' tag so they show up under the 'JWT key' section in the references
- moved the endpoints to lower in the file so they show up lower down in the reference guide
=> chore: add JWT key tag to the JWT endpoints

api/api.yaml, api/generated/api.json
Enabled proxy.enabled to be updated on UpdateInstallation endpoint
=> [Customer Support] Proxy enabled

api/api.yaml, api/generated/api.json
- Added notes on the delay on subscribe action update.
=> Add update note for subscribe action update

api/api.yaml, api/generated/api.json
See https://ampersand.slab.com/posts/metadata-custom-field-creation-api-proposal-oarwgavc
Related server PR: https://github.com/amp-labs/server/pull/3950
=> [ENG-2483] feat: add endpoints and schemas for upsertmetadata operations
