amp-labs/openapi

- Makefile
The README refers to a make command which doesn't exist. This PR adds that.
> Add a makefile with the lint command

- api/api.yaml
Test below
```
make lint
cd api && rdme openapi:validate write.yaml && cd ..
write.yaml is a valid OpenAPI API definition!
cd api && rdme openapi:validate api.yaml && cd ..
api.yaml is a valid OpenAPI API definition!
cd config && rdme openapi:validate config.yaml && cd ..
config.yaml is a valid OpenAPI API definition!
cd catalog && rdme openapi:validate catalog.yaml && cd ..
catalog.yaml is a valid OpenAPI API definition!
cd manifest && rdme openapi:validate manifest.yaml && cd ..
manifest.yaml is a valid OpenAPI API definition!
cd problem && rdme openapi:validate problem.yaml
problem.yaml is a valid OpenAPI API definition!
```
> Fix catalog link from api.yaml

- catalog/catalog.yaml
breaking changes:
- `audience` is now an array of strings (see https://www.ory.sh/docs/hydra/guides/audiences)
- renamed `apiKeyOpts.type` to `attachmentType`
- put query param and header info in their objects nested under `apiKeyOpts`
- the `api_key` authType enum is now `apiKey` (We were mixing up camel case and snakecase for enums. e.g. oauth2opts.grantType was camel case. We generally prefer camel case.)
non-breaking:
- added optional docsURL to Oauth2Opts
- added descriptions to a bunch of fields
Filed https://linear.app/ampersand/issue/ENG-1284/modify-connectors-to-accommodate-breaking-changes-in-auth-related for updating the connectors that are affected by these breaking changes.
> breaking: modify oauth2Opts and apiKeyOpts

- api/api.yaml
Certain auth types don't have the oauth callback as part of the setup. Which means that connections don't get created automatically, which means that we need an endpoint to do this explicitly. This describes the endpoint necessary. Note that the body is about 85% ripped off from the oauth-connect endpoint.
> feat: Add the connections:generate endpoint

- catalog/catalog.yaml
- Allows setting certain headers in the catalog that can be passed in with an OAuth2 auth request
> [ENG-1268] Allow passing extra headers in OAuth2 AuthURL

- api/write.yaml
> fix: wrong example for write mode

- api/api.yaml
This PR adds missing fields so that credentials can be submitted to the connections:generate endpoint
> feat: Add keys for alternative auth types

- Makefile
- api/read.yaml
Test
```
jaehyunlim@Jaehyuns-MBP openapi % make lint
cd api && rdme openapi:validate write.yaml && cd ..
write.yaml is a valid OpenAPI API definition!
cd api && rdme openapi:validate read.yaml && cd ..
read.yaml is a valid OpenAPI API definition!
cd api && rdme openapi:validate api.yaml && cd ..
api.yaml is a valid OpenAPI API definition!
cd config && rdme openapi:validate config.yaml && cd ..
config.yaml is a valid OpenAPI API definition!
cd catalog && rdme openapi:validate catalog.yaml && cd ..
catalog.yaml is a valid OpenAPI API definition!
cd manifest && rdme openapi:validate manifest.yaml && cd ..
manifest.yaml is a valid OpenAPI API definition!
cd problem && rdme openapi:validate problem.yaml
problem.yaml is a valid OpenAPI API definition!
```
> [ENG-1299] Read.yaml for read route

- api/api.yaml
- api/generated/api.json
- package.json
- call Ampersand Console the Ampersand Dashboard instead
- make the engine requirement not as strict, no need to require the exact version of pnpm, there's also no need to require a specific node version since even pnpm itself does not specify a node verion: https://github.com/pnpm/pnpm/blob/96821291a816464ef8f77745a4a77249cdec6b94/package.json#L64
> build: relax engine requirements and also use Dashboard instead of Console terminology

- api/generated/api.json
- catalog/catalog.yaml
A lot of brands have light/dark themed icons and logos, so we should accomodate for that.
> Add light/dark theme options for media

- api/generated/api.json
- manifest/manifest.yaml
As stated,  openapi definition for createInstallation endpoint had backfill definition, but integrationObject did not because they were differently typed. Updating the object definition. 
- build and lint succeeded.
> [bug] fix: Batchupsert to take backfill definition

- Makefile
- manifest/manifest.yaml
As stated. using duplicate backfill definition
make lint, make gen
> Bug: update manifest with duplicate backfill definition

- api/generated/api.json
- catalog/catalog.yaml
At some point it would be good to know when a catalog was generated. The top-level `CatalogType` entity doesn't allow for this additional metadata. This adds a new structure which will hold (a) the timestamp, and (b) the catalog.
The intention is to have `CatalogDescriptor` be the top-level type, but everything else can continue to just operate on `CatalogType`
> feat: Add `CatalogDescriptor`, a catalog wrapper type

- api/api.yaml
- api/generated/api.json
Since project ID is already in the request path, we should not have it in the request body also. Corresponding server change in https://github.com/amp-labs/server/pull/1416
> fix: Remove projectId from generateConnection request body

- api/generated/api.json
- catalog/catalog.yaml
There are several providers now which ostensibly have API keys, but for whatever reason choose to encode their API keys as basic authentication.
This makes the UI confusing, and it makes validation difficult (some actually use, for example, username=$apiKey,password=\<blank\> -- which the UI struggles with).
This modifies the schema for basic auth so that we can eventually support "basic auth masquerading as API key" style authentication. The backend will 100% consider these basic auth, but the frontend will now be able to present a more intuitive layout, and hide the complexity from the end user.
> [ENG-1424] feat: Add `apiKeyLike` and `apiKeyFormat` to `BasicAuthOpts`

- api/generated/api.json
- catalog/catalog.yaml
There's a conflict with enum names (username and password) with another type.
This isn't a problem, but oapi-codegen sees the clash and disambiguates the two by renaming both with long prefixes.
This breaks the existing code. It's easier to just de-conflict the var names explicitly, which avoids this breakage.
This also moves the description field in a few places to their actual valid places. Putting them next to $ref will just be ignored.
> feat: Set the enum var names explicitly

- api/api.yaml
- api/generated/api.json
See title. Fairly straightforward change.
> feat: Add a `scopes` field to `oauth2ClientCredentials` and `oauth2Password`

- api/api.yaml
- api/generated/api.json
- api/generated/read.json
- api/generated/write.json
- api/read.yaml
- api/write.yaml
Api reference pages in docs now show api headers correctly:
> [ENG-1471] fix: ensure `x-api-key` is populated in oai spec & docs

- api/api.yaml
- api/generated/api.json
Our existing API reference is totally wrong, since the server implementation expects a fully formed LatestRevision object, and does not do any parsing of URLs or yaml strings. https://github.com/amp-labs/server/blob/ce750cc6844dcb57e785a33e5aad5f528514b048/api/routes/integration.go#L49
(Only batchUpsertIntegrations will parse yaml)
> fix: correct the request body for CreateIntegration

- webhook/webhook.yaml
1) The `action` field seems to be missing from the webhook definition.
2) Any properties at the same level at `$ref` are ignored. Moved `description` properties to the components being referred to.
3) Currently, the `ResultEntry` schema has defined field and raw maps as `map[string]string`, but we can receive maps from APIs that have fields like - 
```
{
"user": {
"id": "1",
"workspace": "foo"
}
}
```
To support builders requesting the `user` field, we should use `map[string]any`. 
4) The `result` field is no longer always required. In the case that we send a URL to the results, it will be absent. Instead, since we will always send `ResultInfo`, we make that required
> chore: add action field to webhook & other fixes

- api/generated/api.json
- manifest/manifest.yaml
This PR adds builder-defined object name mapping fields to the hydrated revision object
> feat: Add builder-defined object name mapping to HydratedIntegrationObject

- webhook/webhook.yaml
The linter didn't run so I ran local linter
```
jaehyunlim@Jaehyuns-MacBook-Pro openapi % make lint
cd api && rdme openapi:validate write.yaml && cd ..
write.yaml is a valid OpenAPI API definition!
cd api && rdme openapi:validate read.yaml && cd ..
read.yaml is a valid OpenAPI API definition!
cd api && rdme openapi:validate api.yaml && cd ..
api.yaml is a valid OpenAPI API definition!
cd config && rdme openapi:validate config.yaml && cd ..
config.yaml is a valid OpenAPI API definition!
cd catalog && rdme openapi:validate catalog.yaml && cd ..
catalog.yaml is a valid OpenAPI API definition!
cd manifest && rdme openapi:validate manifest.yaml && cd ..
manifest.yaml is a valid OpenAPI API definition!
cd problem && rdme openapi:validate problem.yaml && cd ..
problem.yaml is a valid OpenAPI API …
```
> [ENG-1637] Move eventType fields into ResultEntry from top level message

- webhook/webhook.yaml
This PR adds a field to contain the installation's "last updated" timestamp, since some receivers need to know this in order to trigger certain processes on their side to update the schemas.
> [ENG-1713] feat: Add installationLastUpdated field

- api/api.yaml
- api/generated/api.json
- All declared paths need to be unique 
- The `GET /destination` path is the same as `POST /destination` / `PATCH /destination` / `DELETE /destination` paths, but has been defined separately because the query params have different data types
- This PR merges both, and renames the query param as `destination`, and adds a description about what we expect
> fix: Path params need to be unique

- api/generated/api.json
- catalog/catalog.yaml
Subscribe action has some configuration that needs to be added to providerInfo, so the schema is updated with new fields.
I ran `make lint` and it was success. Also `api.json` compiled successfully.
> [ENG-1890] Provider Info Schema update for Subscribe Action

- api/api.yaml
- api/generated/api.json
- api/generated/read.json
- api/generated/write.json
- api/read.yaml
- api/write.yaml
Some operations require a request body, but do not say that in the spec.
> fix: add missing required tags to request bodies

- api/api.yaml
- api/generated/api.json
- api/generated/read.json
- api/generated/write.json
- api/read.yaml
- api/write.yaml
- catalog/catalog.yaml
- config/config.yaml
- manifest/manifest.yaml
- problem/problem.yaml
- webhook/webhook.yaml
Speakeasy uses titles for generating class names, adding these to make the class names better
> chore: add titles for better sdk class names

- api/api.yaml
- api/generated/api.json
switches oauth update to use a patch requests and updates path.
- relaxes pnpm dep to allow version 10
> fix: oauth-update patch request

- api/generated/api.json
- config/config.yaml
- config/generated/config.json
the `read` and `write` generated types were previously set as `any`, the config object will be exposed now; so need to double check these types are correct.
> fix: use $ref for read and write config

- api/generated/api.json
- catalog/catalog.yaml
- catalog/generated/catalog.json
Something I've noticed is that customers will authenticate, and the oauth flow will complete, but they gave us the wrong workspace name. We won't notice this until after the auth process (e.g. during a read, or during a subscribe webhook). This is obviously inconvenient to debug, and un-intuitive from a UX perspective. It would be much more intuitive to take the credentials and then immediately try an endpoint, to know for 100% certain that all the details we have are going to work. And obviously if it fails, we can return a 4xx status to let the caller know that there's something wrong and the connection won't work.
This adds an optional endpoint the catalog can specify which will eventually be used during the auth process. Once we get a token (or an API key or whatever) we can hit this …
> feat: Add credentialsHealthCheck

- api/generated/api.json
- catalog/catalog.yaml
- catalog/generated/catalog.json
Unfortunately, the oauth2 package doesn't expose the raw token, so we cannot do a nice jq selection over it. We have to use a dot notation to access a specific field using the `token.Extra(metadataFieldPath)` helper that the package gives us, and then transform it.
> chore: use two keys for token metadata extraction

- api/generated/api.json
- config/config.yaml
- config/generated/config.json
Reverts amp-labs/openapi#157
Reintroducing this PR, since reverting it did not fix the Mintlify deployment: https://github.com/amp-labs/docs/runs/41770704902
> Revert "Revert "fix: use $ref for read and write config""

- api/generated/write.json
- api/write.yaml
This adds an optional field for write errors which lets us return the original response body that we get from the provider.
> [ENG-2284] feat: Include original error message in return payload

- api/generated/api.json
- config/config.yaml
- config/generated/config.json
This make the go type to become *[]string
We run validation on the struct and validation library panics for that type. So we will remove tag here and do manual validation in server
> Remove validation for config requiredWatchFields 

- api/generated/api.json
- catalog/catalog.yaml
- catalog/generated/catalog.json
This adds a few tags to the go structures for a specific field (valueTemplate) which we can use to key off of in order to decide whether or not to do substitutions.
> add go tags for valueTemplate so that substitutions will be skipped

- api/generated/api.json
- catalog/catalog.yaml
- catalog/generated/catalog.json
This PR introduces the default values for metadata.
Modified ProviderInfo of Microsoft such that single tenant as well as multitenant can be selected.
For backwards compatability AuthURL and TokenURL must default to `common` "workspace".
I tried specifying and omitting workspace metadata and got expected values:
> feat(api-types): Default metadata value

- api/generated/api.json
- config/config.yaml
- config/generated/config.json
- manifest/generated/manifest.json
- manifest/manifest.yaml
Previously we made destination and schedule optional, but by doing so made the go type to be poitner. This PR fixes it.
> Schedule and Destination optional pointer true

- api/api.yaml
- api/generated/api.json
Fixed indentation for orgUpdate and invite so that it lines up with other parts of the code. API docs correctly appear.
> [ENG-2525] fixed indentation error for orgUpdate and invite

- api/generated/api.json
- catalog/generated/catalog.json
- webhook/generated/webhook.json
- webhook/webhook.yaml
Added new fields to WebhookMessage schema:
* consumerRef - The reference ID of the consumer that triggered the webhook (required)
* consumerName - The name of the consumer that triggered the webhook (required)
* operationTime - Set to time.Now() when webhook is sent (optional since only set for read webhooks)
Must be deploeyd before https://github.com/amp-labs/server/pull/3987
> [ENG-2541] feat: Updated webhook.yaml in the openai repo
